package com.werare.proxy

import java.io.*
import java.net.*
import kotlin.concurrent.thread
import kotlin.random.Random

class ProxyEngine(private val server: ProxyServer, private val lagMs:Int=0, private val lossPercent:Int=0) {
    @Volatile var running=false; private set
    private var serverSocket:ServerSocket?=null
    fun start(localPort:Int=10808){ if(running)return; running=true; thread { try { serverSocket=ServerSocket(localPort,64,InetAddress.getByName("127.0.0.1")); while(running){ val c=try{serverSocket!!.accept()}catch(_:Exception){if(!running)break else continue}; thread {try{handle(c)}catch(_:Exception){}finally{runCatching{c.close()}}} } }catch(_:Exception){} } }
    fun stop(){running=false;runCatching{serverSocket?.close()}}
    private fun handle(c:Socket){ val i=DataInputStream(c.getInputStream()); val o=c.getOutputStream(); i.readUnsignedByte(); val n=i.readUnsignedByte(); val methods=ByteArray(n);i.readFully(methods); o.write(byteArrayOf(5,0));o.flush(); val h=ByteArray(4);i.readFully(h); if(h[1].toInt()!=1)return; val host=when(h[3].toInt() and 255){1->ByteArray(4).also{i.readFully(it)}.joinToString("."){(it.toInt()and 255).toString()};3->{val l=i.readUnsignedByte();ByteArray(l).also{i.readFully(it)}.toString(Charsets.UTF_8)};4->{val b=ByteArray(16);i.readFully(b);InetAddress.getByAddress(b).hostAddress};else->return}; val pb=ByteArray(2);i.readFully(pb);val port=((pb[0].toInt()and255)shl8)or(pb[1].toInt()and255); val up=Socket();up.connect(InetSocketAddress(server.host,server.port),15000); if(!connectUpstream(up,host,port)){up.close();return};o.write(byteArrayOf(5,0,0,1,0,0,0,0,0,0));o.flush();relay(c,up)}
    private fun connectUpstream(s:Socket,host:String,port:Int):Boolean=when(server.type.uppercase()){"HTTP","HTTPS"->httpConnect(s,host,port);"SOCKS4","SOCKS4A"->socks4Connect(s,host,port);else->socks5Connect(s,host,port)}
    private fun httpConnect(s:Socket,host:String,port:Int):Boolean{val o=s.getOutputStream();val i=s.getInputStream();o.write("CONNECT $host:$port HTTP/1.1\r\nHost: $host:$port\r\nConnection: Keep-Alive\r\n\r\n".toByteArray());o.flush();val b=ByteArray(4096);val n=i.read(b);return n>0&&String(b,0,n).lineSequence().firstOrNull()?.contains(" 200 ")==true}
    private fun socks4Connect(s:Socket,host:String,port:Int):Boolean{val o=s.getOutputStream();val i=s.getInputStream();val ip=runCatching{InetAddress.getByName(host).address}.getOrNull();val user=(server.user?:("" )).toByteArray();if(ip!=null){o.write(byteArrayOf(4,1,(port shr8).toByte(),port.toByte(),ip[0],ip[1],ip[2],ip[3]));o.write(user);o.write(0);o.flush()}else{val h=host.toByteArray();o.write(byteArrayOf(4,1,(port shr8).toByte(),port.toByte(),0,0,0,1));o.write(user);o.write(0);o.write(h);o.write(0);o.flush()};val r=ByteArray(8);i.readFully(r);return r[1].toInt()and255==90}
    private fun socks5Connect(s:Socket,host:String,port:Int):Boolean{val o=s.getOutputStream();val i=DataInputStream(s.getInputStream());val need=!server.user.isNullOrEmpty();o.write(byteArrayOf(5,1,(if(need)2 else 0).toByte()));o.flush();val r=ByteArray(2);i.readFully(r);if(r[1].toInt()and255==255)return false;if(r[1].toInt()and255==2){val u=(server.user?:("" )).toByteArray();val p=(server.pass?:("" )).toByteArray();o.write(byteArrayOf(1,u.size.toByte())+u+byteArrayOf(p.size.toByte())+p);o.flush();val a=ByteArray(2);i.readFully(a);if(a[1].toInt()!=0)return false};val h=host.toByteArray();o.write(byteArrayOf(5,1,0,3,h.size.toByte())+h+byteArrayOf((port shr8).toByte(),port.toByte()));o.flush();val resp=ByteArray(4);i.readFully(resp);if(resp[1].toInt()!=0)return false;when(resp[3].toInt()and255){1->repeat(4){i.readByte()};3->repeat(1+i.readUnsignedByte()){i.readByte()};4->repeat(16){i.readByte()}};i.readByte();i.readByte();return true}
    private fun relay(a:Socket,b:Socket){val x=thread{pump(a.getInputStream(),b.getOutputStream())};val y=thread{pump(b.getInputStream(),a.getOutputStream())};while(running&&x.isAlive&&y.isAlive)Thread.sleep(100);runCatching{a.close()};runCatching{b.close()}}
    private fun pump(i:InputStream,o:OutputStream){val b=ByteArray(8192);try{while(running){val n=i.read(b);if(n<0)break;if(lagMs>0)Thread.sleep(lagMs.toLong());if(lossPercent>0&&Random.nextInt(100)<lossPercent)continue;o.write(b,0,n);o.flush()}}catch(_:Exception){}}
}
